from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, JSON, ForeignKey, Text
from sqlalchemy.orm import relationship
from app.database import Base
from app.models.base import TimestampMixin, generate_uuid, get_utc_now


class AIModelRegistryEntry(Base, TimestampMixin):
    """Stores metadata and governance details for active and archived AI/ML models."""
    __tablename__ = "ai_model_registry"

    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    model_name = Column(String(100), nullable=False, unique=True, index=True)
    model_version = Column(String(50), nullable=False, index=True)
    model_type = Column(String(50), nullable=False)  # random_forest, rule_dss, gradient_boosting, regression
    accuracy = Column(Float, nullable=False, default=0.85)
    f1_score = Column(Float, nullable=True, default=0.85)
    dataset_version = Column(String(50), nullable=True, default="v2026.1")
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    artifact_path = Column(String(255), nullable=True)
    checksum_sha256 = Column(String(64), nullable=True)
    metadata_json = Column(JSON, nullable=True)


class DisasterRiskPredictionRecord(Base, TimestampMixin):
    """Audit log of disaster risk assessments generated by the Risk Prediction Engine."""
    __tablename__ = "disaster_risk_predictions"

    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    disaster_type = Column(String(50), nullable=False, index=True)
    location_name = Column(String(200), nullable=False)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    risk_score = Column(Float, nullable=False, index=True)  # 0 to 100
    risk_level = Column(String(30), nullable=False, index=True)  # LOW, MODERATE, HIGH, CRITICAL
    confidence = Column(Float, nullable=False, default=0.85)
    input_parameters = Column(JSON, nullable=False)
    risk_factors = Column(JSON, nullable=False)
    recommendations = Column(JSON, nullable=False)
    model_version = Column(String(50), nullable=False, default="v1.0.0-hybrid-dss")
    created_by_user_id = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    # Relationships
    created_by = relationship("User", foreign_keys=[created_by_user_id])


class ResourceForecastRecord(Base, TimestampMixin):
    """Stores resource supply demand forecasts and inventory shortage gaps."""
    __tablename__ = "resource_forecasts"

    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    disaster_type = Column(String(50), nullable=False, index=True)
    severity = Column(Float, nullable=False)
    population_affected = Column(Integer, nullable=False)
    forecast_period_hours = Column(Integer, nullable=False, default=24)
    predicted_demand = Column(JSON, nullable=False)
    inventory_gap = Column(JSON, nullable=False)
    recommendations = Column(JSON, nullable=False)
    organization_id = Column(String(36), ForeignKey("organizations.id", ondelete="SET NULL"), nullable=True, index=True)
    created_by_user_id = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    # Relationships
    organization = relationship("Organization", foreign_keys=[organization_id])
    created_by = relationship("User", foreign_keys=[created_by_user_id])


class DisasterSimulationRecord(Base, TimestampMixin):
    """Stores administrator disaster impact simulations and contingency models."""
    __tablename__ = "disaster_simulations"

    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    scenario_title = Column(String(150), nullable=False, index=True)
    disaster_type = Column(String(50), nullable=False, index=True)
    severity = Column(Float, nullable=False)
    population_affected = Column(Integer, nullable=False)
    duration_hours = Column(Integer, nullable=False)
    location_name = Column(String(200), nullable=False)
    simulation_results = Column(JSON, nullable=False)
    created_by_user_id = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    # Relationships
    created_by = relationship("User", foreign_keys=[created_by_user_id])
